Praha20191113.Web/Models/MoviesViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Praha20191113.Web.Models
{
    public class MoviesViewModel
    {
        public int Id { get; set; }
        //[Display(Name ="MovieTitle", ResourceType =typeof(Localiza))]
        [Required]
        public string Title { get; set; }
        public Genre Genre { get; set; }
        [DataType(DataType.Date)]
        public DateTime? ReleasedDate { get; set; }
        public string Director { get; set; }
        public string Language { get; set; }
    }

    public enum Genre
    {
        //[Display(Name = "Hokus pokus")]
        Comedy,
        //[Display(Name = "Hokus pokus Thriller")]
        Thriller
    }
}

Praha20191113.Web/Controllers/HelloWorldController.cs
using System.Web.Mvc;

namespace Praha20191113.Web.Controllers
{
    public class HelloWorldController : Controller
    {
        // GET: HelloWorld
        public ActionResult Index()
        {
            var model = "Hello World22!!";
            return View(model: model);
        }
    }
}

Praha20191113.Web/Controllers/MoviesController.cs
using Praha20191113.Web.Models;
using Praha20191113.Web.Services;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Praha20191113.Web.Controllers
{
    public class MoviesController : BaseController
    {
        public MoviesController(ILogger logger, ApplicationDbContext context) : base(logger, context)
        {
        }

        public ActionResult Details(int id)
        {
            var dbMovieToShowDetail = Db.Movies.Find(id);
            if (dbMovieToShowDetail == null)
            {
                throw new Exception("Cannot find movie to edit");
            }

            var movieViewModelToShowDetail = new MoviesViewModel()
            {
                Id = dbMovieToShowDetail.Id,
                Title = dbMovieToShowDetail.Title,
                Genre = dbMovieToShowDetail.Genre,
                ReleasedDate = dbMovieToShowDetail.ReleasedDate,
            };

            return View(movieViewModelToShowDetail);
        }

        public ActionResult Index()
        {
            var movies = Db.Movies.ToList();

            var viewModels = movies.Select(movie => new MoviesViewModel()
            {
                Id = movie.Id,
                Genre = movie.Genre,
                ReleasedDate = movie.ReleasedDate,
                Title = movie.Title,
                Director = movie.Director,
                Language = movie?.Language?.Name
            });

            return View(viewModels.ToList());
        }

        public ActionResult Released(string year, string month)
        {
            var parsedDateTime = DateTime.Parse($"{year}/{month}");

            var filteredMovies = Db.Movies.Where(movie => movie.ReleasedDate >= parsedDateTime);

            var filteredMoviesViewModel = filteredMovies.Select(dbMovie => new MoviesViewModel()
            {
                Id = dbMovie.Id,
                Genre = dbMovie.Genre,
                ReleasedDate = dbMovie.ReleasedDate,
                Title = dbMovie.Title,
                Director = dbMovie.Director,
            });

            Db.SaveChanges();

            return View(filteredMoviesViewModel.ToList());
        }


        [Authorize]
        public ActionResult Create()
        {
            return View(new MoviesViewModel());
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create(MoviesViewModel movieToCreate)
        {
            if (!ModelState.IsValid)
            {
                return View(movieToCreate);
            }

            Db.Movies.Add(new Movie()
            {
                Genre = movieToCreate.Genre,
                Title = movieToCreate.Title,
                ReleasedDate = movieToCreate.ReleasedDate,
                Director = movieToCreate.Director,
            });

            Db.SaveChanges();
            TempData["Message"] = "Movie was successfully created";
            return this.RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var dbMovieToEdit = Db.Movies.SingleOrDefault(movie => movie.Id == id);
            if (dbMovieToEdit == null)
            {
                throw new Exception("Cannot find movie to edit");
            }

            var movieViewModelToEdit = new MoviesViewModel()
            {
                Id = dbMovieToEdit.Id,
                Title = dbMovieToEdit.Title,
                Genre = dbMovieToEdit.Genre,
                ReleasedDate = dbMovieToEdit.ReleasedDate,
                Director = dbMovieToEdit.Director
            };

            return View(movieViewModelToEdit);
        }

        [HttpPost]
        public ActionResult Edit(MoviesViewModel movieViewModelToEdit)
        {
            if (!ModelState.IsValid)
            {
                return View(movieViewModelToEdit);
            }

            var dbMovieToEdit = Db.Movies.Find(movieViewModelToEdit.Id);
            if (dbMovieToEdit == null)
            {
                throw new Exception("Cannot find movie in database");
            }

            dbMovieToEdit.Genre = movieViewModelToEdit.Genre;
            dbMovieToEdit.ReleasedDate = movieViewModelToEdit.ReleasedDate;
            dbMovieToEdit.Title = movieViewModelToEdit.Title;
            dbMovieToEdit.Director = movieViewModelToEdit.Director;
            Db.SaveChanges();

            return View(movieViewModelToEdit);
        }

        public ActionResult Delete(int id)
        {
            var dbMovieToDelete = Db.Movies.Find(id);
            if (dbMovieToDelete == null)
            {
                throw new Exception("Cannot find movie to delete");
            }

            var movieViewModelToDelete = new MoviesViewModel()
            {
                Id = dbMovieToDelete.Id,
                Title = dbMovieToDelete.Title,
                Genre = dbMovieToDelete.Genre,
                ReleasedDate = dbMovieToDelete.ReleasedDate,
                Director = dbMovieToDelete.Director,
            };

            return View(movieViewModelToDelete);
        }


        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(MoviesViewModel moviesViewModel)
        {
            var dbMovieToDelete = Db.Movies.Find(moviesViewModel.Id);

            Db.Movies.Remove(dbMovieToDelete);

            Db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

Praha20191113.Web/Views/Shared/_BlueLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top background-blue">
        <div class="container">
            <div class="navbar-header" style="color:red">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Hello Wordl", "Index", "HelloWorld")</li>
                    @RenderSection("previousAction", false)
                    <li>@Html.ActionLink("Movies", "Details", "Movies", new { id = 0 }, null)</li>
                    @RenderSection("nextAction", false)
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Praha20191113.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Hello Wordl", "Index", "HelloWorld")</li>
                    <li>@Html.ActionLink("Movies", "Details", "Movies", new { id = 0 }, null)</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        $(function () {
            $(".datefield").datepicker();
        });
    </script>

</body>
</html>

Praha20191113.Web/Views/Shared/_MoviesTable.cshtml
@model IEnumerable<MoviesViewModel>
@{
    ViewBag.Title = "_MoviesTable";
}

<h2>_MoviesTable</h2>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Movie title</th>
            <th>Movie Genre</th>
            <th>Released Data</th>
            <th>Director</th>
            <th>Show Detail</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var movie in Model)
        {
        <tr>
            <td>@movie.Id</td>
            <td>@movie.Title</td>
            <td>@movie.Genre</td>
            <td>@movie.ReleasedDate</td>
            <td>@movie.Director</td>
            <td>
                <button class="btn btn-primary" onclick="location.href='@Url.Action("Details", "Movies", new { id = movie.Id })'">
                    Show Detail
                </button>
                <a href="@Url.Action("Details", "Movies", new { id = movie.Id })" class="btn btn-primary">text</a>

                @Html.ActionLink("DShiw de", "Details", "Movies", new { id = movie.Id }, new { @class = "btn btn-primary" })
            </td>
        </tr>
        }

    </tbody>
</table>